spring:
  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener_db?useSSL=false&serverTimezone=UTC
    username: ENC(DxQtXDllyrdEskO+ks2zVF3Tbi4eG5UDdwexklfDzp+v9iU4gWDAo3b/hAbk5VJF)
    password: ENC(gvT30LmfIiuD/v3mDhPvPi0ZmOIf+/8TWKqgIN9XbpvELQ8FirVTbTJqb5yZRCtS)
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates/updates tables based on entities
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: localhost
    port: 6379
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64
logging:
  level:
    org.jasypt: DEBUG
    com.github.ulisesbocchio: TRACE
    org.springframework: DEBUG